name = "quotebot"
type = "webpack"
account_id = "b989c18bd2f4829d4997fa5ce5ba66aa"
workers_dev = true
route = ""
zone_id = "73d3828c320fda8e674c174277ddb981"
webpack_config = "webpack.config.js"

[env.production]
