name = "quotebot"
type = "javascript"
account_id = "b989c18bd2f4829d4997fa5ce5ba66aa"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"